[package]
name = "frontrunner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
comfy-table = "7.1.1"
odbc = "0.17.0"
serialport = "4.5.0"
simplelog = "0.12.2"
log = "0.4.22"
